# Generated by Django 4.2.19 on 2025-02-13 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinhSach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Tên chính sách')),
                ('content', models.TextField(verbose_name='Nội dung')),
            ],
        ),
        migrations.CreateModel(
            name='GiaVatLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('kimcuong', 'Kim Cương'), ('vang', 'Vàng'), ('bac', 'Bạc'), ('platinum', 'Platinum'), ('Cubic_Zirconia', 'Cubic Zirconia'), ('Cubic Zirconia', 'Cubic Zirconia'), ('Ruby', 'Ruby'), ('Emerald', 'Emerald')], max_length=200, null=True, verbose_name='Tên vật liệu')),
                ('price', models.FloatField(verbose_name='Giá')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('PAYMENT', 'Payment Policy'), ('CANCELLATION', 'Cancellation Policy')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
        ),
    ]
