# Generated by Django 5.0.11 on 2025-02-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giavatlieu',
            name='name',
            field=models.CharField(choices=[('kimcuong', 'Kim Cương'), ('vang', 'Vàng'), ('bac', 'Bạc'), ('platinum', 'Platinum'), ('Cubic_Zirconia', 'Cubic Zirconia'), ('Cubic Zirconia', 'Cubic Zirconia'), ('Ruby', 'Ruby'), ('Emerald', 'Emerald')], max_length=200, null=True, verbose_name='Tên vật liệu'),
        ),
    ]
