# Generated by Django 5.0.10 on 2025-01-24 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField()),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='product')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='product')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='product')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='product')),
                ('type', models.CharField(blank=True, choices=[('ring', 'Ring Product'), ('earring', 'Earring Product'), ('bracelet', 'Bracelet Product'), ('pendant', 'Pendant Product'), ('gemstone', 'Gemstone Product'), ('collection', 'Collection Product')], max_length=20, null=True)),
                ('design', models.CharField(blank=True, choices=[('design_img', 'Design Image Product'), ('design_3d', 'Design 3D Product')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(blank=True, choices=[('nam', 'Nam'), ('nu', 'Nữ'), ('khac', 'Khác')], max_length=20, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_oder', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('DangXuLy', 'Đang xử lý'), ('DaTiepNhan', 'Đã tiếp nhận'), ('DangGiao', 'Đang giao'), ('DaGiao', 'Đã giao')], max_length=20, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, choices=[('diamond', 'Diamond'), ('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum')], max_length=20, null=True)),
                ('TrangSucDinhKem', models.CharField(blank=True, choices=[('ring', 'Ring'), ('earring', 'Earring'), ('bracelet', 'Bracelet'), ('pendant', 'Pendant')], max_length=20, null=True)),
                ('Daphu', models.CharField(blank=True, choices=[('Cubic Zirconia', 'Cubic Zirconia'), ('Moissanite', 'Moissanite')], max_length=20, null=True)),
                ('DaTam', models.CharField(blank=True, choices=[('Ruby', 'Ruby'), ('Emerald', 'Emerald')], max_length=20, null=True)),
                ('Size', models.CharField(blank=True, choices=[('16cm', '16cm'), ('17cm', '17cm'), ('18cm', '18cm'), ('19cm', '19cm'), ('20cm', '20cm'), ('21cm', '21cm'), ('22cm', '22cm'), ('23cm', '23cm'), ('24cm', '24cm'), ('25cm', '25cm')], max_length=20, null=True)),
                ('Describe', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product')),
            ],
        ),
    ]
