# Generated by Django 5.0.11 on 2025-02-04 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Tiêu đề')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Nội dung')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='Hình ảnh')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Tên sản phẩm')),
                ('price', models.FloatField()),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Hình ảnh chính')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Hình ảnh 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Hình ảnh 3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Hình ảnh 4')),
                ('type', models.CharField(blank=True, choices=[('ring', 'Ring Product'), ('earring', 'Earring Product'), ('bracelet', 'Bracelet Product'), ('pendant', 'Pendant Product'), ('gemstone', 'Gemstone Product'), ('collection', 'Collection Product')], max_length=20, null=True, verbose_name='Loại sản phẩm')),
                ('design', models.CharField(blank=True, choices=[('design_img', 'Design Image Product'), ('design_3d', 'Design 3D Product')], max_length=20, null=True, verbose_name='Thiết kế')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa chỉ')),
                ('sex', models.CharField(blank=True, choices=[('nam', 'Nam'), ('nu', 'Nữ'), ('khac', 'Khác')], max_length=20, null=True, verbose_name='Giới tính')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Số điện thoại')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
        ),
        migrations.CreateModel(
            name='Oder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_oder', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt hàng')),
                ('status', models.CharField(blank=True, choices=[('DangXuLy', 'Đang xử lý'), ('DaTiepNhan', 'Đã tiếp nhận'), ('DangGiao', 'Đang giao'), ('DaGiao', 'Đã giao')], max_length=20, null=True, verbose_name='Trạng thái')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Số lượng')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer', verbose_name='Khách hàng')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product', verbose_name='Sản phẩm')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, choices=[('diamond', 'Diamond'), ('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum')], max_length=20, null=True, verbose_name='Chất liệu')),
                ('TrangSucDinhKem', models.CharField(blank=True, choices=[('ring', 'Ring'), ('earring', 'Earring'), ('bracelet', 'Bracelet'), ('pendant', 'Pendant')], max_length=20, null=True, verbose_name='Trang sức đính kèm')),
                ('Daphu', models.CharField(blank=True, choices=[('Cubic Zirconia', 'Cubic Zirconia'), ('Moissanite', 'Moissanite')], max_length=20, null=True, verbose_name='Đá phụ')),
                ('DaTam', models.CharField(blank=True, choices=[('Ruby', 'Ruby'), ('Emerald', 'Emerald')], max_length=20, null=True, verbose_name='Đá tâm')),
                ('Size', models.CharField(blank=True, choices=[('16cm', '16cm'), ('17cm', '17cm'), ('18cm', '18cm'), ('19cm', '19cm'), ('20cm', '20cm'), ('21cm', '21cm'), ('22cm', '22cm'), ('23cm', '23cm'), ('24cm', '24cm'), ('25cm', '25cm')], max_length=20, null=True, verbose_name='Size')),
                ('Describe', models.TextField(blank=True, null=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product', verbose_name='Sản phẩm')),
            ],
        ),
    ]
