# Generated by Django 5.0.10 on 2025-02-09 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Giá'),
        ),
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=20, null=True, verbose_name='Chất liệu')),
                ('TrangSucDinhKem', models.CharField(blank=True, max_length=20, null=True, verbose_name='Trang sức đính kèm')),
                ('Daphu', models.CharField(blank=True, max_length=20, null=True, verbose_name='Đá phụ')),
                ('DaTam', models.CharField(blank=True, max_length=20, null=True, verbose_name='Đá tâm')),
                ('Size', models.CharField(blank=True, max_length=20, null=True, verbose_name='Size')),
                ('Describe', models.TextField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.oder', verbose_name='Đơn hàng')),
            ],
        ),
    ]
