# Generated by Django 5.0.11 on 2025-02-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên sản phẩm'),
        ),
    ]
