# Generated by Django 5.0.10 on 2025-01-23 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product'),
        ),
        migrations.CreateModel(
            name='Product_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, choices=[('diamond', 'Diamond'), ('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum')], max_length=20, null=True)),
                ('TrangSucDinhKem', models.CharField(blank=True, choices=[('ring', 'Ring'), ('earring', 'Earring'), ('bracelet', 'Bracelet'), ('pendant', 'Pendant')], max_length=20, null=True)),
                ('Daphu', models.CharField(blank=True, choices=[('Cubic Zirconia', 'Cubic Zirconia'), ('Moissanite', 'Moissanite')], max_length=20, null=True)),
                ('DaTam', models.CharField(blank=True, choices=[('Ruby', 'Ruby'), ('Emerald', 'Emerald')], max_length=20, null=True)),
                ('Size', models.CharField(blank=True, choices=[('16cm', '16cm'), ('17cm', '17cm'), ('18cm', '18cm'), ('19cm', '19cm'), ('20cm', '20cm'), ('21cm', '21cm'), ('22cm', '22cm'), ('23cm', '23cm'), ('24cm', '24cm'), ('25cm', '25cm')], max_length=20, null=True)),
                ('Describe', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product')),
            ],
        ),
    ]
