# Generated by Django 5.0.10 on 2025-01-24 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_details_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Tiêu đề')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Nội dung')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='Hình ảnh')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.CharField(blank=True, choices=[('nam', 'Nam'), ('nu', 'Nữ'), ('khac', 'Khác')], max_length=20, null=True, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='oder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer', verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='oder',
            name='date_oder',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt hàng'),
        ),
        migrations.AlterField(
            model_name='oder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='oder',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='oder',
            name='status',
            field=models.CharField(blank=True, choices=[('DangXuLy', 'Đang xử lý'), ('DaTiepNhan', 'Đã tiếp nhận'), ('DangGiao', 'Đang giao'), ('DaGiao', 'Đã giao')], max_length=20, null=True, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='product',
            name='design',
            field=models.CharField(blank=True, choices=[('design_img', 'Design Image Product'), ('design_3d', 'Design 3D Product')], max_length=20, null=True, verbose_name='Thiết kế'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Hình ảnh chính'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Hình ảnh 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Hình ảnh 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Hình ảnh 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Tên sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('ring', 'Ring Product'), ('earring', 'Earring Product'), ('bracelet', 'Bracelet Product'), ('pendant', 'Pendant Product'), ('gemstone', 'Gemstone Product'), ('collection', 'Collection Product')], max_length=20, null=True, verbose_name='Loại sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='DaTam',
            field=models.CharField(blank=True, choices=[('Ruby', 'Ruby'), ('Emerald', 'Emerald')], max_length=20, null=True, verbose_name='Đá tâm'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='Daphu',
            field=models.CharField(blank=True, choices=[('Cubic Zirconia', 'Cubic Zirconia'), ('Moissanite', 'Moissanite')], max_length=20, null=True, verbose_name='Đá phụ'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='Size',
            field=models.CharField(blank=True, choices=[('16cm', '16cm'), ('17cm', '17cm'), ('18cm', '18cm'), ('19cm', '19cm'), ('20cm', '20cm'), ('21cm', '21cm'), ('22cm', '22cm'), ('23cm', '23cm'), ('24cm', '24cm'), ('25cm', '25cm')], max_length=20, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='TrangSucDinhKem',
            field=models.CharField(blank=True, choices=[('ring', 'Ring'), ('earring', 'Earring'), ('bracelet', 'Bracelet'), ('pendant', 'Pendant')], max_length=20, null=True, verbose_name='Trang sức đính kèm'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='material',
            field=models.CharField(blank=True, choices=[('diamond', 'Diamond'), ('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum')], max_length=20, null=True, verbose_name='Chất liệu'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product', verbose_name='Sản phẩm'),
        ),
    ]
