# Generated by Django 5.0.10 on 2025-01-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_image_product_mau_image_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='D_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/static/home/img/mau'),
        ),
    ]
