# Generated by Django 5.1.3 on 2025-01-27 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VaiTro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_vai_tro",
                    models.CharField(max_length=50, verbose_name="Tên vai trò"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NguoiDung",
            fields=[
                (
                    "id_nguoi_dung",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ten_nguoi_dung",
                    models.CharField(max_length=50, verbose_name="Tên người dùng"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("mat_khau", models.CharField(max_length=128, verbose_name="Mật khẩu")),
                (
                    "vai_tro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.vaitro"
                    ),
                ),
            ],
        ),
    ]
