version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "QU@NG123sp"
      MSSQL_PID: "Developer"
    ports:
      - "11433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./wait-for-it.sh", "-t", "60", "db:1433", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mssql_data: