# Generated by Django 5.0.12 on 2025-02-27 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blog_alter_customer_address_alter_customer_phone_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('status', models.CharField(max_length=50, verbose_name='Trạng thái')),
                ('date_ordered', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt hàng')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer', verbose_name='Khách hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product', verbose_name='Sản phẩm')),
            ],
        ),
    ]
